# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e41b969524ef0422222f9c983bafd16b129435e4a7277b60f2202695069af312fb2723cd3d73e6de1c28ca15428fcb38cacc2807867ed1b66c5d1635dbf55b

test:
  secret_key_base: c202dc8015cd3a5556655c521fa3d0ea1f6e79e33716d1777d4acdfe39edf198766ce3440724f048c51e6057e068ccadf0a720d20a1ebc3e66b00384377f1863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
